Fix/unsafe arithmetics
hashed-io/hashed-pallets pull request #42
Opened 2024-03-21 19:16 UTC by didiermis

# Title of changes made: [Fix] Avoiding arithmetic overflows in key scaling operations

## Overview

The primary goal of the changes is to mitigate potential arithmetic overflows while performing some vital scaling operations in the "Afloat" and "Fund-Admin" pallets. The purpose is to ensure the safety of mathematical computations and maintain data integrity across the systems.

This PR adds some "safe" arithmetic functions to add, multiply amounts or perform other arithmetic operations without risking any overflow. Whenever such functions are called, they check if the given operation would result in an overflow. If true, it returns an error before executing the operation.

The changes were mainly targeting the "create_tax_credit()" in the "Afloat" Pallet and "calculate_drawdown_total_amount()" and "calculate_revenue_total_amount()" in the "Fund-Admin" Pallet.

## Tickets

Fix #31

## Implementation notes

The implementation involves two significant changes:

1. Addition of the safe arithmetic functions, "safe_add()" and "safe_multiply_offer()". These functions perform the mathematical operation and check for a potential overflow. If the operation would result in an overflow, they short-circuit and return an `ArithmeticOverflow` error.

2. Integration of the newly
3. created safe arithmetic functions into the existing logic. The safe functions are called before performing mathematical calculations in "create_tax_credit()" in  "Afloat" Pallet and "calculate_drawdown_total_amount()" and "calculate_revenue_total_amount()" in the "Fund-Admin" Pallet. If an overflow is detected, the functions will return an error, stopping the operation and preserving the integrity of the system.

## Interesting/controversial decisions

The changes performed might have some tradeoffs in terms of performance since we are checking for potential arithmetic overflow for each operation. However, these checks are essential to maintain the integrity of the system and avoid any data corruption. Additionally, the checks for overflow should have minimum performance impact since they are straightforward and fast to compute.

## Test coverage

The changes include testing of the newly added functionality. In the "Afloat" pallets, we tested the potential overflow using the "replicate_overflow_for_start_take_sell_order()" function, and in the "Fund-Admin" pallets, we used the "replicate_overflow_for_a_drawdown_submission()" and "replicate_overflow_for_a_revenue_submission()". These tests can effectively detect and prevent any arithmetic overflow during the operations.

## Loose ends

This PR doesn't cover every potential overflow scenario. Other parts of the codebase may also benefit from the addition of similar safe arithmetic operations.

2024-03-21 20:23 UTC, sebastianmontero requested changes

2024-03-21 20:23 UTC, sebastianmontero commented on pallets/afloat/src/functions.rs
> +		Self::safe_multiply_offer(offer.price_per_credit, tax_credit_amount)?;
Deberiamos de utilizar el resultado de esta operacion, en lugar de hacer la multiplicacion otra vez

2024-03-21 20:23 UTC, sebastianmontero commented on pallets/afloat/src/functions.rs
> +	fn safe_multiply_offer(
La funcion deberia de devolver el resultado, para poder utilizarlo

2024-03-21 20:23 UTC, sebastianmontero commented on pallets/fund-admin/src/functions.rs
> -		ensure!(
Por que se elimino este check?

2024-03-21 20:23 UTC, sebastianmontero commented on pallets/fund-admin/src/functions.rs
> +	fn safe_add(a: u64, b: u64) -> DispatchResult {
la funcion debería de devolver el resultado para poder utilizarlo

2024-03-21 20:23 UTC, sebastianmontero commented on pallets/fund-admin/src/functions.rs
> +				Self::safe_add(drawdown_total_amount, transaction_data.amount)?;
Deberiamos de utlizar el resultado  de esta operacion, en lugar de hacer la operacion otra vez

2024-03-21 20:23 UTC, sebastianmontero commented on pallets/fund-admin/src/functions.rs
> +				Self::safe_add(revenue_total_amount, revenue_transaction_data.amount)?;
Deberiamos de utlizar el resultado de esta operacion, en lugar de hacer la operacion otra vez

2024-03-21 23:04 UTC, didiermis commented on pallets/afloat/src/functions.rs
> +		Self::safe_multiply_offer(offer.price_per_credit, tax_credit_amount)?;
Listo.

2024-03-21 23:04 UTC, didiermis commented on pallets/afloat/src/functions.rs
> +	fn safe_multiply_offer(
Listo.

2024-03-21 23:05 UTC, didiermis commented on pallets/fund-admin/src/functions.rs
> -		ensure!(
Estaba repetido, m{as abajo se vuelve a validar.

2024-03-21 23:05 UTC, didiermis commented on pallets/fund-admin/src/functions.rs
> +	fn safe_add(a: u64, b: u64) -> DispatchResult {
Listo.

2024-03-21 23:05 UTC, didiermis commented on pallets/fund-admin/src/functions.rs
> +				Self::safe_add(drawdown_total_amount, transaction_data.amount)?;
Listo.

2024-03-21 23:05 UTC, didiermis commented on pallets/fund-admin/src/functions.rs
> +				Self::safe_add(revenue_total_amount, revenue_transaction_data.amount)?;
Listo.

2024-03-22 00:07 UTC, sebastianmontero requested changes

2024-03-22 00:07 UTC, sebastianmontero commented on pallets/afloat/src/functions.rs
> +		let total_price: T::Balance = Self::safe_multiply_offer(price_per_credit, tax_credit_amount)?;
mover esta sentencia arriba del ensure en la linea 478, para poder utilizar el valor de la variable en el ensure

2024-03-22 00:07 UTC, sebastianmontero commented on pallets/fund-admin/src/functions.rs
> -		ensure!(
Ok, movamos el ensure antes de crear el RevenueTransactionData por favor

2024-03-22 14:39 UTC, didiermis commented on pallets/afloat/src/functions.rs
> +		let total_price: T::Balance = Self::safe_multiply_offer(price_per_credit, tax_credit_amount)?;
Listo.

2024-03-22 19:26 UTC, sebastianmontero commented on pallets/fund-admin/src/functions.rs
> -		ensure!(
Falta este cambio

2024-03-22 19:26 UTC, sebastianmontero commented on pallets/afloat/src/functions.rs
> +		let total_price: T::Balance = Self::safe_multiply_offer(price_per_credit, tax_credit_amount)?;
Falta este cambio

2024-03-22 19:27 UTC, sebastianmontero requested changes
No veo los cambios que habia solicitados

2024-03-22 21:51 UTC, sebastianmontero approved these changes

2024-03-22 21:52 UTC, merged