Developed benchmarks and weights for afloat, closes #36
hashed-io/hashed-pallets pull request #43
Opened 2024-04-01 15:17 UTC by Dreyhh

* Developed benchmarks and weights for afloat pallet.
* Changed Fruniques's Attributes type to a BoundedVec.

2024-04-02 23:25 UTC, sebastianmontero requested changes

2024-04-02 23:25 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +	fn sign_up() {
Para este benchmark habría que tomar en cuenta la llamada a assign_role_to_user de la pallet RBAC, considerando el peor caso, que seria Scopes y Pallet Roles estan al maximo, y RolesByUser and UsersByScope estan por llegar al limite.

2024-04-02 23:25 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +	fn update_user_info() {
El benchmark lo deberiamos de hacer sobre el UpdateUserArgs::Delete, ya que es el peor caso

2024-04-02 23:25 UTC, sebastianmontero commented on pallets/afloat/src/lib.rs
> +			tax_credit_amount: u32,
Por que se le cambio el tipo al parametro?

2024-04-02 23:25 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +	fn create_tax_credit(a: Linear<0, { <T as pallet_fruniques::Config>::MaxAttributes::get() }>) {
Para este benchmark, creo que habria que considerar cual es el pero caso para fruinques::do_spawn y correrlo bajo esas condiciones

2024-04-02 23:25 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +	fn start_take_sell_order() {
Para este benchmark creo que una de las variables deberia de ser el numero de transacciones existentes para una oferta. Ver la propiedad transactions de offer

2024-04-02 23:25 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +	fn confirm_sell_transaction() {
Para este benchmark, creo que habria que considerar cual es el pero caso para gated_marketplace::do_enlist_sell_offer y correrlo bajo esas condiciones

2024-04-02 23:25 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +	fn finish_take_sell_transaction() {
Para este benchmark, creo que habria que considerar cual es el pero caso para gated_marketplace::do_take_sell_offer y correrlo bajo esas condiciones

2024-04-02 23:25 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +	fn add_afloat_admin() {
Para este benchmark, creo que habria que considerar cual es el pero caso para rbac::assign_role_to_user y correrlo bajo esas condiciones

2024-04-02 23:25 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +	fn assign_user_to_role() {
Para este benchmark, creo que habria que considerar cual es el pero caso para rbac::assign_role_to_user y correrlo bajo esas condiciones

2024-04-04 16:30 UTC, Dreyhh commented on pallets/afloat/src/benchmarking.rs
> +	fn sign_up() {
done, se añadio una llamada set_rbac_assign_role_to_user_worst_case

2024-04-04 16:31 UTC, Dreyhh commented on pallets/afloat/src/benchmarking.rs
> +	fn update_user_info() {
done

2024-04-04 16:32 UTC, Dreyhh commented on pallets/afloat/src/lib.rs
> +			tax_credit_amount: u32,
Reverted, no era un cambio que queria incluir

2024-04-04 16:33 UTC, Dreyhh commented on pallets/afloat/src/benchmarking.rs
> +	fn create_tax_credit(a: Linear<0, { <T as pallet_fruniques::Config>::MaxAttributes::get() }>) {
done, se añadio una llamada a `set_up_fruniques_do_spawn_worst_case()`

2024-04-04 16:36 UTC, Dreyhh commented on pallets/afloat/src/benchmarking.rs
> +	fn start_take_sell_order() {
crees que deba ser una variable? no es un parametro que podamos obtener directamente de los argumentos de la extrinsic, añadi una llamada a `set_start_take_sell_offer_worst_case()`

2024-04-04 16:37 UTC, Dreyhh commented on pallets/afloat/src/benchmarking.rs
> +	fn confirm_sell_transaction() {
done, se añadio una llamada a `set_gm_do_enlist_sell_offer_worst_case`

2024-04-04 17:45 UTC, Dreyhh commented on pallets/afloat/src/benchmarking.rs
> +	fn finish_take_sell_transaction() {
done, se añadio una llamada a `set_up_fruniques_do_spawn_worst_case()` ( usado por gated_marketplace::do_take_sell_offer ) las otra condiciones ya se cumplen ( tax credit amount < 100 y al menos una oferta existente)

2024-04-04 17:45 UTC, Dreyhh commented on pallets/afloat/src/benchmarking.rs
> +	fn assign_user_to_role() {
done

2024-04-04 17:48 UTC, Dreyhh commented
@sebastianmontero aun no actualizo los weights, lo hare cuando tenga luz verde con los benchmarks

2024-04-04 17:49 UTC, Dreyhh commented on pallets/afloat/src/benchmarking.rs
> +	fn add_afloat_admin() {
done

2024-04-05 14:56 UTC, sebastianmontero requested changes

2024-04-05 14:56 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +		let new_cid: ShortString = ShortString::try_from(generate_vector(0, 1, LSS)).unwrap();
Deberiamos de borrar estas variables que no se usan

2024-04-05 14:56 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +	fn update_user_info() {
Para el peor caso habria que considerar que se estan borrando roles, no solo de la palleta de afloat, sino tambien the gated market place y fruniques

2024-04-05 14:56 UTC, sebastianmontero commented on pallets/afloat/src/benchmarking.rs
> +fn set_gm_do_enlist_sell_offer_worst_case<T: Config>(
Creo que falta considerar MaxOffersPerMarket, que deben de ser mayor a max offers per item

2024-04-09 19:59 UTC, sebastianmontero approved these changes

2024-04-09 20:02 UTC, merged

2024-04-09 20:17 UTC, Dreyhh commented
@sebastianmontero no habia generado los weigths actualizados con los ultimos cambios, esperaba confirmacion con benchmarks, abrire otra PR para incluirlos.