Benchmarks Fund admin pallet
hashed-io/hashed-pallets pull request #44
Opened 2024-04-05 20:47 UTC by didiermis

2024-04-08 17:49 UTC, sebastianmontero requested changes

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn users(
Para este benchmark, creo que habria que considerar cual es el pero caso para rbac::assign_role_to_user y correrlo bajo esas condiciones. Ver: https://github.com/hashed-io/hashed-pallets/blob/bd05e7f7a708c83d6ef493f85c47e276ee20a661/pallets/afloat/src/benchmarking.rs#L53

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn users_edit_user(
Para simplificar el benchmark creo que todas las variables relacionadas a la longitud de campos (todas las que son de 1 a 100) las podemos agrupar en 1 sola variable.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +		x: Linear<1, { T::MaxRegistrationsAtTime::get() }>,
por que tenemos esta variable si no se utliza?

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn projects_create_project(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.
- agrupar todas variables que son de 1 a 400 en 1 sola variable.

Deberiamos de correr benchmark con el ProjectsByUser al limite, es decir con el vector al MAX - 1, para probar el peor caso.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn projects_edit_project(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.
- agrupar todas variables que son de 1 a 400 en 1 sola variable.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +		e: Linear<1, { T::MaxBanksPerProject::get() }>,
por que tenemos esta variable si no se utliza?

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +		h: Linear<1, { T::MaxRegistrationsAtTime::get() }>,
por que tenemos esta variable si no se utliza?

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn projects_delete_project() {
Deberiamos de correr benchmark con el ProjectsByUser al limite, es decir con el vector al MAX, para probar el peor caso.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn projects_assign_user(
Para este benchmark, creo que habria que considerar cual es el pero caso para rbac::assign_role_to_user y correrlo bajo esas condiciones. Ver: https://github.com/hashed-io/hashed-pallets/blob/bd05e7f7a708c83d6ef493f85c47e276ee20a661/pallets/afloat/src/benchmarking.rs#L53

Deberiamos de correr benchmark con el ProjectsByUser al limite, es decir con el vector al MAX - 1, para probar el peor caso.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn expenditures_and_job_eligibles(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.
- agrupar todas variables que son de 1 a 400 en 1 sola variable.

Deberiamos de considerar el peor caso para ExpendituresByProject, es decir los nuevos expenditures que se agreguen deberian de llevar a ExpendituresByProject a MaxExpendituresPerProject.

Deberiamos de considerar el peor caso para JobEligiblesByProject, es decir los nuevos job eligibles que se agreguen deberian de llevar a JobEligiblesByProject a MaxJobEligiblesPerProject.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn submit_drawdown(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.

Deberiamos de considerar el peor caso para TransactionsByDrawdown, es decir las nuevas transacciones que se agreguen deberian de llevar a TransactionsByDrawdown a MaxTransactionsPerDrawdown.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn approve_drawdown(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.

Deberiamos de considerar el peor caso para TransactionsByDrawdown, es decir las nuevas transacciones que se agreguen deberian de llevar a TransactionsByDrawdown a MaxTransactionsPerDrawdown.

Deberiamos de considerar el peor caso para DrawdownsByProject, es decir los nuevos drawdowns que se agreguen deberian de llevar a DrawdownsByProject a MaxDrawdownsPerProject.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +		let admin = initialize_pallet::<T>(100);
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 400 en 1 sola variable.

Deberiamos de considerar el peor caso para TransactionsByDrawdown, que es cuando tiene MaxTransactionsPerDrawdown y deberia de haber feedback para el mayor numero de transacciones posible

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn up_bulkupload(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn submit_revenue(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.

Deberiamos de considerar el peor caso para TransactionsByRevenue, es decir las nuevas transacciones que se agreguen deberian de llevar a TransactionsByRevenue a MaxTransactionsPerRevenue.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn approve_revenue() {
Deberiamos de considerar el peor caso para TransactionsByRevenue, debe estar al MaxTransactionsPerRevenue.

Deberiamos de considerar el peor caso para RevenuesByProject, es decir los nuevos revenues que se agreguen deberian de llevar a RevenuesByProject a MaxRevenuesPerProject.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +		let admin = initialize_pallet::<T>(100);
Deberiamos de considerar el peor caso para TransactionsByRevenue, que es cuando tiene MaxTransactionsPerRevenue y deberia de haber feedback para el mayor numero de transacciones posible

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn bank_confirming_documents(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.

Deberiamos de considerar el peor caso para TransactionsByDrawdown, que es cuando tiene MaxTransactionsPerDrawdown

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn reset_drawdown() {
Deberiamos de considerar el peor caso para TransactionsByDrawdown, que es cuando tiene MaxTransactionsPerDrawdown

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn recovery_drawdown(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.

Deberiamos de considerar el peor caso para TransactionsByDrawdown, es decir las nuevas transacciones que se agreguen deberian de llevar a TransactionsByDrawdown a MaxTransactionsPerDrawdown.

2024-04-08 17:49 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn recovery_revenue(
Para simplificar el benchmark: 
- agrupar todas variables que son de 1 a 100 en 1 sola variable.

Deberiamos de considerar el peor caso para TransactionsByRevenue, es decir las nuevas transacciones que se agreguen deberian de llevar a TransactionsByRevenue a MaxTransactionsPerRevenue.

2024-04-15 19:37 UTC, Dreyhh commented on pallets/fund-admin/src/benchmarking.rs
> +	fn users(
Luego de realizar cambios similares en el benchmark de afloat, y notar que el pov de los weigths generados permanacio sin cambios, investigue un poco mas y encontre esta breve discusion : https://substrate.stackexchange.com/questions/8902/how-does-the-benchmark-calculate-the-proof-size
TLDR: mientras que es cierto que el size de los StorageMaps ( y de sus valores ) es de importancia para los weigths, las condiciones para el peor caso son recreadas automaticamente a lo hora de generar los benchmarks para todos los types involucrados que implementen el trait de MaxEcondedLen, debido a que el `pov_mode` default es MaxEcondedLen, esto puede comprobarse en los comentarios de las funciones weigths generadas al correr los benchmarks, eg: https://github.com/hashed-io/hashed-pallets/blob/7d30e9795dc0c1d45d04260b1c75115fc7a96c33/pallets/afloat/src/weights.rs#L73

2024-04-15 21:07 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn users(
Gracias Armando! Muy bueno saberlo, actualicemos los benchmarks, para tomarlo en cuenta.

2024-04-16 15:58 UTC, Dreyhh commented on pallets/fund-admin/src/benchmarking.rs
> +	fn users_edit_user(
creo que es buena idea simplificar cuando sea posible pero tal vez debemos preservar al menos N variables si la extrinsic acepta N argumentos, aunque sus rangos sean los mismos, ya que a la hora de llamar la funcion del weigth debemos pasarle los los valores que relamente toman, la otra opcion seria simplemente tomar la maxima longitud para todos y que el PostDispatchInfo se encargue de la correcion si es necesaria, que opinas?

2024-04-16 16:16 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn users_edit_user(
Si quieres probemoslo como comentas, pero creo que si son muchos argumentos el benchmark va a correr muy lento, pero hagamos la prueba y si no nada mas usemos el maximo.

2024-04-16 16:27 UTC, Dreyhh commented on pallets/fund-admin/src/benchmarking.rs
> +	fn users_edit_user(
Si, creo que lo mejor es usar los maximos, igual si agrupamos las variables al final acabariamos pasando los maximos a la funcion weigth y no tendria caso que sean variables. Tal vez solo dejar como variables aquellos vectores en los que hagamos operaciones costosas como iteraciones y no sean solo alocar memoria como los CIDs y Nombres

2024-04-16 18:31 UTC, sebastianmontero commented on pallets/fund-admin/src/benchmarking.rs
> +	fn users_edit_user(
De acuerdo

2024-04-22 23:08 UTC, sebastianmontero approved these changes

2024-04-22 23:09 UTC, merged