Developed benchmarks and generated weights for pallet gated-marketplace
hashed-io/hashed-pallets pull request #47
Opened 2024-04-26 22:05 UTC by Dreyhh

# Benchmarks and weights for gated marketplace

## Overview
* Adds benchmarks and weights for gated marketplace

### Tickets

List the tickets of the PR linked
- [ ] Fix #37

2024-04-30 20:37 UTC, sebastianmontero requested changes

2024-04-30 20:37 UTC, sebastianmontero commented on pallets/gated-marketplace/src/benchmarking.rs
> +	fn remove_marketplace() {
Creo que en este caso si tendriamos que agregar el numero maximo de aplicaciones y custodians, ya que se itera cada una para borrarla

2024-04-30 23:51 UTC, Dreyhh commented on pallets/gated-marketplace/src/benchmarking.rs
> +	fn remove_marketplace() {
Parece que niguno de los storagemaps en los que se itera (en esa extrinsic) tiene definido un limite, los valores de custodians tiene limite pero no se itera sobre ellos. De todos modos checare los demas extrinsics, me parece que para el de remover offertas si aplica

2024-05-01 20:26 UTC, Dreyhh commented
@sebastianmontero hice los cambios para popular los valores algunos de los storage maps en los que se itera, no hubo cambios significantes al volver a calcular los weigths, tal vez debido a que los limites que manejamos en el runtime no son grandes. Hay algunos storage maps en los que se itera directamente pero no tienen limite definido.

2024-05-01 23:25 UTC, sebastianmontero requested changes

2024-05-01 23:25 UTC, sebastianmontero commented on pallets/gated-marketplace/src/benchmarking.rs
> +	fn remove_marketplace() {
Tienes razon, creo que de todos modos seria importante ver como el numero de applicaciones afecta el weight del extrinsic, creo que deberiamos de agregar una variable al benchmark para el numero de applicaciones, despues podemos pasar un valor razonable a la funcion de WeightInfo, como ves?

2024-05-02 17:13 UTC, Dreyhh commented on pallets/gated-marketplace/src/benchmarking.rs
> +	fn remove_marketplace() {
Tiene sentido, seria definir pseudolimites, uno por cada SM en el que se itere, y pasarle valores razonables "VR" < a esos limites a la funcion de weight, la desventaje es que tendriamos que estar pendiente de los valores reales para actualizarlo una vez estos superen a los VR (o a los pseudolimites), pero por lo demas creo que es buena idea si queremos dejar esos SM sin limite.

2024-05-06 15:26 UTC, sebastianmontero approved these changes

2024-05-06 15:26 UTC, merged